SEARCH_DIR("/home/bernd/Programme/Laz-ESP8266/cross/lib/xtensa-freertos/lx106/")
SEARCH_DIR("/home/bernd/Programme/Laz-ESP8266/cross/bin/xtensa-freertos/esp-rtos-3.4/components/esp8266/ld/")
SEARCH_DIR("./")
SEARCH_DIR("/home/bernd/Programme/Laz-ESP8266/fpc/units/xtensa-freertos/lx106/rtl/")
SEARCH_DIR("/home/bernd/Programme/Laz-ESP8266/cross/units/esp8266-idf/")
SEARCH_DIR("/home/bernd/Programme/Laz-ESP8266/cross/units/additionally/")
SEARCH_DIR("/home/bernd/Programme/Laz-ESP8266/fpc/units/xtensa-freertos/lx106/")
SEARCH_DIR("/home/bernd/Programme/Laz-ESP8266/fpc/units/xtensa-freertos/")
SEARCH_DIR("/home/bernd/Programme/Laz-ESP8266/fpc/bin/x86_64-linux/")
INPUT (
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/SpiffExample.o
/home/bernd/Programme/Laz-ESP8266/fpc/units/xtensa-freertos/lx106/rtl/system.o
/home/bernd/Programme/Laz-ESP8266/fpc/units/xtensa-freertos/lx106/rtl/objpas.o
/home/bernd/Programme/Laz-ESP8266/fpc/units/xtensa-freertos/lx106/rtl/esp8266.o
/home/bernd/Programme/Laz-ESP8266/fpc/units/xtensa-freertos/lx106/rtl/consoleio.o
/home/bernd/Programme/Laz-ESP8266/fpc/units/xtensa-freertos/lx106/rtl/heapmgr.o
/home/bernd/Programme/Laz-ESP8266/fpc/units/xtensa-freertos/lx106/rtl/esp8266rtos_30400.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/fmem.o
/home/bernd/Programme/Laz-ESP8266/fpc/units/xtensa-freertos/lx106/rtl/ctypes.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/esp_err.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/esp_log2.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/laz_esp.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/esp_spiffs.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/task.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/portmacro.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/uart.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/lwip_ip4_addr.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/lwip_ip_addr.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/lwip_def.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/lwip_udp.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/lwip_err.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/lwip_arch.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/lwip_opt.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/lwip_pbuf.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/lwip_netif.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/lwip_ip.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/lwip_prot_udp.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/lwipopts.o
/home/bernd/Programme/Laz-ESP8266/fpc/units/xtensa-freertos/lx106/rtl/sysutils.o
/home/bernd/Programme/Laz-ESP8266/fpc/units/xtensa-freertos/lx106/rtl/sysconst.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/lwip_prot_ip4.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/lwip_ip4.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/lwip_prot_ip.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/lwip_stats.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/lwip_mem.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/lwip_memp.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/queue.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/freertos.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/projdefs.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/xtensa_rtos.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/hal.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/portable.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/list.o
/home/bernd/Sprachen/Lazarus/64_bit/Meine_Packages/ESP_8266/ESP8266/Demo_Projekte/22_SpiffsExample_01/lib/xtensa-freertos/esp_heap_caps.o
)
GROUP(
/home/bernd/Programme/Laz-ESP8266/cross/lib/xtensa-freertos/lx106/libspiffs.a
/home/bernd/Programme/Laz-ESP8266/cross/lib/xtensa-freertos/lx106/libc.a
/home/bernd/Programme/Laz-ESP8266/cross/lib/xtensa-freertos/lx106/libesp8266.a
/home/bernd/Programme/Laz-ESP8266/cross/lib/xtensa-freertos/lx106/liblog.a
/home/bernd/Programme/Laz-ESP8266/cross/lib/xtensa-freertos/lx106/libnewlib.a
/home/bernd/Programme/Laz-ESP8266/cross/lib/xtensa-freertos/lx106/libc_nano.a
/home/bernd/Programme/Laz-ESP8266/cross/lib/xtensa-freertos/lx106/libheap.a
/home/bernd/Programme/Laz-ESP8266/cross/lib/xtensa-freertos/lx106/libvfs.a
/home/bernd/Programme/Laz-ESP8266/cross/lib/xtensa-freertos/lx106/libesp_common.a
/home/bernd/Programme/Laz-ESP8266/cross/lib/xtensa-freertos/lx106/libcore.a
/home/bernd/Programme/Laz-ESP8266/cross/lib/xtensa-freertos/lx106/libfreertos.a
/home/bernd/Programme/Laz-ESP8266/cross/lib/xtensa-freertos/lx106/libphy.a
/home/bernd/Programme/Laz-ESP8266/cross/lib/xtensa-freertos/lx106/libnet80211.a
/home/bernd/Programme/Laz-ESP8266/cross/lib/xtensa-freertos/lx106/libhal.a
/home/bernd/Programme/Laz-ESP8266/cross/lib/xtensa-freertos/lx106/libnvs_flash.a
/home/bernd/Programme/Laz-ESP8266/cross/lib/xtensa-freertos/lx106/librtc.a
/home/bernd/Programme/Laz-ESP8266/cross/lib/xtensa-freertos/lx106/libspi_flash.a
/home/bernd/Programme/Laz-ESP8266/cross/lib/xtensa-freertos/lx106/libesp_ringbuf.a
/home/bernd/Programme/Laz-ESP8266/cross/lib/xtensa-freertos/lx106/libgcc.a
/home/bernd/Programme/Laz-ESP8266/cross/lib/xtensa-freertos/lx106/libpp.a
/home/bernd/Programme/Laz-ESP8266/cross/lib/xtensa-freertos/lx106/libstdc++.a
/home/bernd/Programme/Laz-ESP8266/cross/lib/xtensa-freertos/lx106/libpthread.a
/home/bernd/Programme/Laz-ESP8266/cross/lib/xtensa-freertos/lx106/libfreertos.a
)
SECTIONS
{
  .data :
  {
    KEEP (*(.fpc .fpc.n_version .fpc.n_links))
  }
}
